version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - contextcheck
    - decorder
    - errorlint
    - exptostd
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - nestif
    - wrapcheck
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
      disable:
        - fieldalignment
    lll:
      line-length: 140
    misspell:
      locale: US

  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: should have a package comment
      - linters:
          - revive
        text: 'unused-parameter'
      - linters:
          - dupl
          - gosec
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
      - mocks$
